In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/healthcare_dataset (2).csv')

In [3]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        1
Discharge Date        1
Medication            1
Test Results          1
dtype: int64

In [5]:
df.shape

(20781, 15)

In [8]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [11]:
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20781 entries, 0 to 20780
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                20781 non-null  object
 1   Age                 20781 non-null  int64
 2   Gender              20781 non-null  object
 3   Blood Type          20781 non-null  object
 4   Medical Condition   20781 non-null  object
 5   Date of Admission   20781 non-null  object
 6   Doctor              20781 non-null  object
 7   Hospital            20781 non-null  object
 8   Insurance Provider  20781 non-null  object
 9   Billing Amount      20781 non-null  float64
 10  Room Number         20781 non-null  int64
 11  Admission Type      20780 non-null  object
 12  Discharge Date      20780 non-null  object
 13  Medication          20780 non-null  object
 14  Test Results        20780 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.4+ MB

In [16]:
categorical_features = [
    'Gender',
    'Blood Type',
    'Medical Condition',
    'Insurance Provider',
    'Admission Type',
    'Medication',
    'Test Results'
]

In [17]:
for col in categorical_features:
    df[col] = df[col].str.strip()

In [23]:
numeric_columns = [
    'Age',
    'Billing Amount',
    'Room Number'
]

In [27]:
print("\nstatistical measures:")

for column in numeric_columns:
  print(f"\n{column}")
  print("Mean:",df[column].mean())
  print("Median:",df[column].median())
  print("Standard Deviation:",df[column].std())
  print("Q1:",df[column].quantile(0.25))
  print("Q2",df[column].quantile(0.50))
  print("Q3",df[column].quantile(0.75))

statistical measures:

Age
Mean: 51.64140320485058
Median: 52.0
Standard Deviation: 19.603227102536437
Q1: 35.0
Q2 52.0
Q3 69.0

Billing Amount
Mean: 25630.86190062868
Median: 25694.504014104827
Standard Deviation: 14190.045182900769
Q1: 13310.81899140126
Q2 25694.504014104827
Q3 37777.4253355352

Room Number
Mean: 300.0899860449449
Median: 301.0
Standard Deviation: 115.15429823763962
Q1: 201.0
Q2 301.0
Q3 398.0