In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")

In [4]:
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10409 entries, 0 to 10408
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10409 non-null  object
 1   Open       10409 non-null  float64
 2   High       10409 non-null  float64
 3   Low        10409 non-null  float64
 4   Close      10409 non-null  float64
 5   Adj Close  10409 non-null  float64
 6   Volume     10409 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 569.4+ KB

In [6]:
df.shape

(10409, 7)

In [7]:
df.shape

(10409, 7)

In [8]:
df.isnull()

        Date   Open   High    Low  Close  Adj Close  Volume
0      False  False  False  False  False      False   False
1      False  False  False  False  False      False   False
2      False  False  False  False  False      False   False
3      False  False  False  False  False      False   False
4      False  False  False  False  False      False   False
...      ...    ...    ...    ...    ...        ...     ...
10404  False  False  False  False  False      False   False
10405  False  False  False  False  False      False   False
10406  False  False  False  False  False      False   False
10407  False  False  False  False  False      False   False
10408  False  False  False  False  False      False   False

[10409 rows x 7 columns]

In [9]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10404    False
10405    False
10406    False
10407    False
10408    False
Length: 10409, dtype: bool

In [10]:
print( df["Open"].mean())
print( df["Close"].mean())

13.959909858007494
13.966756942837927

In [11]:
df["Daily_return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100

In [12]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_return
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.456591
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.492580
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000
...,...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200,2.161860
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400,1.143667
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000,1.999886
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700,1.321508
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700,1.759622